### ISSUE TITLE
Missing 贅沢 and the kanji for かわいそう (可哀相)

### ISSUE THREAD

**Issue by BlueRaja** [Doublevil/JmdictFurigana#15]
In addition to the above very common ones, the following are marked "common" by Jisho.org:
平壌
水俣病
高麗
西藏

And these are uncommon ones:
蒔絵
正木
筑子
桔梗
御飯 (when pronounced 「おんいい」)
愛媛県
烏龍茶

Most of them are names of places or scientific names. You said last time you didn't care about names, but I'm not sure if that extends to "names of places".  Regardless, the two in the title aren't names.

**Comment by Doublevil** [comment]
Fair enough for 贅沢. I'm going to add ぜい as a reading for 贅.
I'm not sure what to do with 可哀相.

All the other ones don't seem useful to add, common or not (commonness is not a factor at all).
As I said last times, there is a huge portion of names that have weird readings, and you have to keep in mind that the aim of this project is to provide character-by-character furigana over words when possible. So if we take for instance 御飯 (おんいい), what would you say the entry should look like? If you want it to be just おんいい over both kanji, I say there is no point in listing it: if it's missing from JmdictFurigana, you should assume that it's a special reading in some ways, so you should put the reading over the whole word, as it cannot be detailed.

As the readme says, some readings cannot be solved because they are not built on normal character readings, and it's just the way the language works.
We add exceptions for stuff like 大人 (おとな), but that's because there are words that build up on these ones, like 大人買い, so having 大人 solved as おとな over both characters helps solve 大人買い as おとな on the two first characters and が on the third one. In these cases, it is useful. But for these place names, there simply is no point.
