### ISSUE TITLE
27 "valid" entries present in the v1 not in the v3 anymore!

### ISSUE THREAD

**Issue by 2small2fall** [Doublevil/JmdictFurigana#5]
Hello,

I've made some processing in my consolidated DB (entries from other sources than jmdict including some french pro/reliable data) and the following valid entries (27) present in the v1 have simply disappeared in the v3, here there are :

"御兄さん","おにいさん","0:お;1:にい","jmdict"
"御姉さん","おねえさん","0:お;1:ねえ","jmdict"
"御母さん","おかあさん","0:お;1:かあ","jmdict"
"抑抑","そもそも","0:そも;1:そも","jmdict"
"犇犇","ひしひし","0:ひし;1:ひし","jmdict"
"険しい路","けわしいみち","0:けわ;3:みち","jmdict"
"芝生","しばふ","0-1:しばふ","jmdict"
"純日本風","じゅんにほんふう","0:じゅん;1-2:にほん;3:ふう","jmdict"
"真珠湾","しんじゅわん","0:しん;1:じゅ;2:わん","jmdict"
"草履","ぞうり","0-1:ぞうり","jmdict"
"大和魂","やまとだましい","0-1:やまと;2:だましい","jmdict"
"竹刀","しない","0-1:しない","jmdict"
"東京湾","とうきょうわん","0:とう;1:きょう;2:わん","jmdict"
"日本学者","にほんがくしゃ","0-1:にほん;2:がく;3:しゃ","jmdict"
"日本製","にほんせい","0-1:にほん;2:せい","jmdict"
"日本側","にほんがわ","0-1:にほん;2:がわ","jmdict"
"日本刀","にほんとう","0-1:にほん;2:とう","jmdict"
"日本風","にほんふう","0-1:にほん;2:ふう","jmdict"
"木ノ葉","このは","0:こ;2:は","jmdict"
"木ノ葉","きのは","0:き;2:は","jmdict"
"余所見","よそみ","0:よ;1:そ;2:み","jmdict"
"嗹","れん","0:れん","jmdict"
"愈愈","いよいよ","0:いよ;1:いよ","jmdict"
"偶偶","たまたま","0:たま;1:たま","jmdict"
"益益","ますます","0:ます;1:ます","jmdict"
"風邪薬","かぜぐすり","0-1:かぜ;2:ぐすり","jmdict"
"日独協会","にちどくきょうかい","0:にち;1:どく;2:きょう;3:かい","jmdict"

Therefore, I recommend you to consolidate your DB and do some sql queries checks each time you download a new jmdict file or generate the furiganas as I don't know if the mismatch comes from the newer jmdict file itself or the jmdictFurigana processing.

Anyhow, let me take the opportunity of this issue report to thank you VERY MUCH for your GREAT contribution!!!
Cheers.

**Comment by Doublevil** [comment]
Hello,
Thank you for your detailed report, I'll look into these entries when I have some time. I'll try to investigate it next weekend.
There's a small number of tests I do whenever I upload a file, but I'm not sure how I could prevent stuff like that from happening in the future. What do you mean by "consolidate your db"? I'm only using the JMDict XML file as a data source (plus some text files for special readings and the likes).
At a glance, the issues you report seem to be related to switching the very small special readings database file for a more comprehensive one. It's just strange that it doesn't contain some of the most obvious ones like 姉 -> ねえ.
Now for the 日本 case: I previously classified it as a special reading of 0-1:にほん, but noticing it wasn't in the comprehensive special readings list, I purposefully removed it from the list. I was pretty sure it would be considered as a 0:に|1:ほん though. My bad! I'll look into it as well to determine the correct instance.

**Comment by BlueRaja** [comment]
> I'm not sure how I could prevent stuff like that from happening in the future.

Unit tests are the usual way

**Comment by Doublevil** [comment]
> Unit tests are the usual way

Sure, and I wrote a couple. But I did not happen to have a test for any item on the list.

**Comment by 2small2fall** [comment]
Have just downloaded the latest "JMdict_e" xml file (174.502 entries) in order to check wether or not the 27 entries are present.

御兄さん (first entry in above list) : present ---> entry 1001830 - rowid 131 (sqlite).
日独協会 (last entry in above list) : not present anymore

Additional random check : 

木ノ葉 (an alternative reading of the entry "1534560" / rowed 46746--> 木の葉) is not present (but present in Tagaini Jisho 1.0.3 as an example which uses jmdict data).

This confirms that even if your new readings DB had some little influence in the processing, the jmdict file was also modified. There's no entry changes history it seems.

On my side, I simply consolidate the DB which I have ; understand : as time goes by, the DB simply grows.

**Comment by yayoo1971** [comment]
Hey!

I have identified a third problem (on my side) as I'm using jmdict_import v0.9 (under OSX) to convert the XML file to sqlite.

ex:

Television (テレビ) is not present in the sqlite db when I can find it in the XML file.

Hum.... I know better understand why I couldn't find most of the loanwords that I know... gosh! :-P

My previous message is valid though, this is just another potential issue for many handling the jmdict db this way.

**Comment by Doublevil** [comment]
I'm not sure I get what you mean, but if that can help, I _do_ update the JMDict XML file every time I'm doing an update to get the most recent data (because JMDict is constantly evolving).
Now of course everyone is free to compile the C# project, replace the JMDict XML file by a newer one, and run the batch to get a newer furigana output file.

**Comment by 2small2fall** [comment]
Let me clarify. You're very right to download and use the latest jmdict db. If I've chosen to consolidate MY db because it is not only because I keep translating some entries in french but I also want to keep valid entries which have been removed from the jmdict for some reasons. And I also use data from other sources so I should compile your project in order to get what I need, yep.

**Comment by fasiha** [comment]
I’d hoped that [JMDICT’s database tool](http://www.edrdg.org/jmdictdb/cgi-bin/srchform.py?svc=jmdict&sid=) would let you search for items that were deleted from JMDICT—maybe they left some rationale for why an entry was deleted but alas, I can’t find `日独協会` anywhere in it. It might be worth searching or writing to the [mailing list](https://groups.yahoo.com/neo/groups/edict-jmdict/info) to ask where the discussion about entry removal is? Thanks for bringing this to wider attention @yayoo1971.

**Comment by Doublevil** [comment]
This is fixed in release 1.4. It was related to multiple issues with the new "special readings" source introduced in 1.3.
There may be other related errors that have slipped through though, so don't hesitate if you catch one.

**Comment by yayoo1971** [comment]
Thanks. Will report if I found an error. 
Have you ever considered to improved the algorithm with the help of MECAB where most of the calculations could be performed? The advantage of MECAB is that you can dynamically parse a text and get the correct furiganas almost instantly also, it's very efficient.
I don't have the time anymore, but I've coded a (to be completed) furigana generator in objective-c years ago...

**Comment by Doublevil** [comment]
Correct me if I'm wrong, but I think MECAB works with a dictionary and identifies words in a text. This is a completely different objective.

**Comment by yayoo1971** [comment]
Right. However, using MECAB + your smart algorithm (mine is not advanced so that I still have it manage many exceptions)

Have a look of what I have achieved with MECAB to that you can see for yourself if you like it.

I would just have to continue to comply my algorithm which is, BTW, why I have ended up finding your repository. 

![simulator screen shot 14 nov 2016 14 11 55](https://cloud.githubusercontent.com/assets/3254992/20266093/c5e05700-aa74-11e6-825b-24b0f1585d41.png)

**Comment by Doublevil** [comment]
Yeah this is not my aim with this project. It aims to be more of a complementary resource for dictionaries, not a parsing tool.
Now of course you can use MECAB along with the JmdictFurigana file and get a nice result, but that's out of the project's scope.

**Comment by yayoo1971** [comment]
As per now, my project is capable of generating correctly a quite high percentage of furiganas thanks to MECAB which provides the correct readings (but also the part of speech and so on). Therefore, it's a matter of exhaustively coding all of the cases and exceptions like what you did in your jmdictfurigana project ; you simply don't need to manipulate data or parse any files thanks to MECAB so that the computation is very fast and the "algorithm" is VERY readable by "anyone" in the code.

MECAB can be helpful and reliable in what you want to achieve I think as I did it ;-)

**Comment by Doublevil** [comment]
I think you are confusing identifying words in a sentence (as does MECAB for example) and identifying kanji readings in a word (JmdictFurigana). The two can work together but they're not the same.

Anyway that's off topic as you said so let's leave the brave issue #5 at that. ;)

**Comment by yayoo1971** [comment]
No, you got me wrong... It's quite clear on my side. ;-)

Alright, let's take an example PART of the #5 issue to come back into the "topic".

jmdictfugirana was giving **"0:にち;1:どく;2:きょう;3:かい"** in the v1.0 (and this entry later disappeared anyway...) which is not correct. Simply look at the furigana processing in my app (see attached screen copy) which is absolutely correct I believe.

The rules which I have coded associated with MECAB (no parsing any file and everything is processed within a single objective-c file!) has matched the correct reading "にちどく" with 日独 (japan & german) when it has failed with jmdictfurigana obviously.

Correct matching also for the other part of the word. きょうかい <-> 協会

So let's face it : two furigana matching mistakes for a single dictionary entry! ;-P

With the MECAB approach, anyone can immediately identify the word as region related (country, province, city, country and so on), an adverb, an adjective, etc while reading the code is GREAT.

Sorry, but I'm trying to contribute in bringing any confusion ; just tried to point you guys to a library which can help you to make your task easier. Anyway, we all have a different approach when it comes to code things.

**Comment by Doublevil** [comment]
I don't think that's right.
Let's take another example because I'm pretty sure 日独協会 does not work quite well in your example.

So, consider something very simple and common, let's say "自由".
- MECAB will recognize it as a word in its database and say "自由 is じゆう".
- JmdictFurigana considers it's a word because it only analyzes individual words. Because it knows each kanji's readings, it's able to say "In 自由, the 自 part is じ and the 由 part is ゆう".

In the same way, JmdictFurigana breaks 協会 as きょう and かい.

So for the last time, this is not a matter of having a different approach, it's just two different goals.
I won't be commenting on this any further now.
Have a nice day.

**Comment by yayoo1971** [comment]
Have a nice day too and all the best with your project.
